// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deploy.proto

package protobuf

/*
target package name
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeployRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Project              string   `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
	Version              string   `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Profile              string   `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	RegistryUrl          string   `protobuf:"bytes,7,opt,name=registryUrl,proto3" json:"registryUrl,omitempty"`
	RemoteUrl            string   `protobuf:"bytes,8,opt,name=remoteUrl,proto3" json:"remoteUrl,omitempty"`
	DockerRegistry       string   `protobuf:"bytes,9,opt,name=dockerRegistry,proto3" json:"dockerRegistry,omitempty"`
	Pipeline             string   `protobuf:"bytes,10,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployRequest) Reset()         { *m = DeployRequest{} }
func (m *DeployRequest) String() string { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()    {}
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_deploy_2efd6d2d55be0ca4, []int{0}
}
func (m *DeployRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployRequest.Unmarshal(m, b)
}
func (m *DeployRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployRequest.Marshal(b, m, deterministic)
}
func (dst *DeployRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployRequest.Merge(dst, src)
}
func (m *DeployRequest) XXX_Size() int {
	return xxx_messageInfo_DeployRequest.Size(m)
}
func (m *DeployRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployRequest proto.InternalMessageInfo

func (m *DeployRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeployRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeployRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DeployRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *DeployRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *DeployRequest) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *DeployRequest) GetRegistryUrl() string {
	if m != nil {
		return m.RegistryUrl
	}
	return ""
}

func (m *DeployRequest) GetRemoteUrl() string {
	if m != nil {
		return m.RemoteUrl
	}
	return ""
}

func (m *DeployRequest) GetDockerRegistry() string {
	if m != nil {
		return m.DockerRegistry
	}
	return ""
}

func (m *DeployRequest) GetPipeline() string {
	if m != nil {
		return m.Pipeline
	}
	return ""
}

type DeployResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployResponse) Reset()         { *m = DeployResponse{} }
func (m *DeployResponse) String() string { return proto.CompactTextString(m) }
func (*DeployResponse) ProtoMessage()    {}
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_deploy_2efd6d2d55be0ca4, []int{1}
}
func (m *DeployResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployResponse.Unmarshal(m, b)
}
func (m *DeployResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployResponse.Marshal(b, m, deterministic)
}
func (dst *DeployResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployResponse.Merge(dst, src)
}
func (m *DeployResponse) XXX_Size() int {
	return xxx_messageInfo_DeployResponse.Size(m)
}
func (m *DeployResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployResponse proto.InternalMessageInfo

func (m *DeployResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeployResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DeployResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*DeployRequest)(nil), "protobuf.DeployRequest")
	proto.RegisterType((*DeployResponse)(nil), "protobuf.DeployResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeployServiceClient is the client API for DeployService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeployServiceClient interface {
	// Sends a greeting
	Run(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error)
}

type deployServiceClient struct {
	cc *grpc.ClientConn
}

func NewDeployServiceClient(cc *grpc.ClientConn) DeployServiceClient {
	return &deployServiceClient{cc}
}

func (c *deployServiceClient) Run(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error) {
	out := new(DeployResponse)
	err := c.cc.Invoke(ctx, "/protobuf.DeployService/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeployServiceServer is the server API for DeployService service.
type DeployServiceServer interface {
	// Sends a greeting
	Run(context.Context, *DeployRequest) (*DeployResponse, error)
}

func RegisterDeployServiceServer(s *grpc.Server, srv DeployServiceServer) {
	s.RegisterService(&_DeployService_serviceDesc, srv)
}

func _DeployService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.DeployService/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployServiceServer).Run(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeployService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.DeployService",
	HandlerType: (*DeployServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _DeployService_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deploy.proto",
}

func init() { proto.RegisterFile("deploy.proto", fileDescriptor_deploy_2efd6d2d55be0ca4) }

var fileDescriptor_deploy_2efd6d2d55be0ca4 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xbb, 0x4e, 0x33, 0x31,
	0x10, 0x85, 0xff, 0x6c, 0xee, 0x93, 0x9f, 0x14, 0x23, 0x24, 0xac, 0x88, 0x22, 0x0a, 0x12, 0xa2,
	0xda, 0x02, 0x3a, 0xca, 0x88, 0x8e, 0x26, 0x5a, 0xc4, 0x03, 0x6c, 0xec, 0x49, 0x62, 0xb2, 0x59,
	0x1b, 0xdb, 0x89, 0x94, 0x07, 0xe2, 0x3d, 0x91, 0x67, 0x2f, 0xdc, 0xaa, 0xf5, 0x39, 0xdf, 0x1c,
	0x69, 0xf6, 0x0c, 0xfc, 0x57, 0x64, 0x0b, 0x73, 0x4e, 0xad, 0x33, 0xc1, 0xe0, 0x88, 0x3f, 0xeb,
	0xe3, 0x66, 0xf1, 0x91, 0xc0, 0xc5, 0x13, 0xa3, 0x8c, 0xde, 0x8f, 0xe4, 0x03, 0x4e, 0x21, 0xd1,
	0x4a, 0x74, 0xe6, 0x9d, 0xbb, 0x71, 0x96, 0x68, 0x85, 0x97, 0xd0, 0x0f, 0x66, 0x4f, 0xa5, 0x48,
	0xd8, 0xaa, 0x04, 0x5e, 0xc3, 0xb8, 0xcc, 0x0f, 0xe4, 0x6d, 0x2e, 0x49, 0x74, 0x99, 0x7c, 0x19,
	0x28, 0x60, 0x68, 0x9d, 0x79, 0x23, 0x19, 0x44, 0x8f, 0x59, 0x23, 0x23, 0x39, 0x91, 0xf3, 0xda,
	0x94, 0xa2, 0x5f, 0x91, 0x5a, 0xd6, 0x99, 0x8d, 0x2e, 0x48, 0x0c, 0xda, 0x4c, 0x94, 0x38, 0x87,
	0x89, 0xa3, 0xad, 0xf6, 0xc1, 0x9d, 0x5f, 0x5d, 0x21, 0x86, 0x4c, 0xbf, 0x5b, 0x71, 0x1b, 0x47,
	0x07, 0x13, 0x28, 0xf2, 0x51, 0xb5, 0x4d, 0x6b, 0xe0, 0x2d, 0x4c, 0x95, 0x91, 0x7b, 0x72, 0x59,
	0x1d, 0x11, 0x63, 0x1e, 0xf9, 0xe5, 0xe2, 0x0c, 0x46, 0x56, 0x5b, 0x2a, 0x74, 0x49, 0x02, 0x78,
	0xa2, 0xd5, 0x8b, 0x0c, 0xa6, 0x4d, 0x4d, 0xde, 0x9a, 0xd2, 0x13, 0x22, 0xf4, 0xa4, 0x51, 0xc4,
	0x4d, 0xf5, 0x33, 0x7e, 0xc7, 0x7f, 0x38, 0x90, 0xf7, 0xf9, 0x96, 0xea, 0xb6, 0x1a, 0x19, 0xa7,
	0x55, 0x1e, 0xf2, 0xba, 0x2a, 0x7e, 0xdf, 0x3f, 0x37, 0xd5, 0xbf, 0x90, 0x3b, 0x69, 0x49, 0xf8,
	0x08, 0xdd, 0xec, 0x58, 0xe2, 0x55, 0xda, 0x9c, 0x27, 0xfd, 0x71, 0x9a, 0x99, 0xf8, 0x0b, 0xaa,
	0x65, 0x16, 0xff, 0x96, 0x37, 0x80, 0xda, 0xa4, 0x3b, 0xad, 0xe8, 0x64, 0xac, 0x4f, 0x77, 0x5a,
	0x6a, 0xa9, 0x96, 0x93, 0x6a, 0x6e, 0x15, 0x63, 0xab, 0xce, 0x7a, 0xc0, 0xf9, 0x87, 0xcf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x28, 0x77, 0x63, 0xaf, 0x0e, 0x02, 0x00, 0x00,
}
