// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dictionary.proto

package protobuf

/*
target package name
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DictionaryRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AppId                int64    `protobuf:"varint,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Type                 int32    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	CreatedBy            int64    `protobuf:"varint,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy            int64    `protobuf:"varint,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedTime          int64    `protobuf:"varint,8,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdateTime           int64    `protobuf:"varint,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Deleted              int32    `protobuf:"varint,10,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DictionaryRequest) Reset()         { *m = DictionaryRequest{} }
func (m *DictionaryRequest) String() string { return proto.CompactTextString(m) }
func (*DictionaryRequest) ProtoMessage()    {}
func (*DictionaryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dictionary_06b32c1b60cef4cf, []int{0}
}
func (m *DictionaryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictionaryRequest.Unmarshal(m, b)
}
func (m *DictionaryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictionaryRequest.Marshal(b, m, deterministic)
}
func (dst *DictionaryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictionaryRequest.Merge(dst, src)
}
func (m *DictionaryRequest) XXX_Size() int {
	return xxx_messageInfo_DictionaryRequest.Size(m)
}
func (m *DictionaryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DictionaryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DictionaryRequest proto.InternalMessageInfo

func (m *DictionaryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DictionaryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DictionaryRequest) GetAppId() int64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *DictionaryRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *DictionaryRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *DictionaryRequest) GetCreatedBy() int64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *DictionaryRequest) GetUpdatedBy() int64 {
	if m != nil {
		return m.UpdatedBy
	}
	return 0
}

func (m *DictionaryRequest) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *DictionaryRequest) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *DictionaryRequest) GetDeleted() int32 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

type DictionaryResponse struct {
	Code                 int32                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*DictionaryRequest `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DictionaryResponse) Reset()         { *m = DictionaryResponse{} }
func (m *DictionaryResponse) String() string { return proto.CompactTextString(m) }
func (*DictionaryResponse) ProtoMessage()    {}
func (*DictionaryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dictionary_06b32c1b60cef4cf, []int{1}
}
func (m *DictionaryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictionaryResponse.Unmarshal(m, b)
}
func (m *DictionaryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictionaryResponse.Marshal(b, m, deterministic)
}
func (dst *DictionaryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictionaryResponse.Merge(dst, src)
}
func (m *DictionaryResponse) XXX_Size() int {
	return xxx_messageInfo_DictionaryResponse.Size(m)
}
func (m *DictionaryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DictionaryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DictionaryResponse proto.InternalMessageInfo

func (m *DictionaryResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DictionaryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DictionaryResponse) GetData() []*DictionaryRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*DictionaryRequest)(nil), "protobuf.DictionaryRequest")
	proto.RegisterType((*DictionaryResponse)(nil), "protobuf.DictionaryResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DictionaryServiceClient is the client API for DictionaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DictionaryServiceClient interface {
	// Sends a greeting
	Get(ctx context.Context, in *DictionaryRequest, opts ...grpc.CallOption) (*DictionaryResponse, error)
}

type dictionaryServiceClient struct {
	cc *grpc.ClientConn
}

func NewDictionaryServiceClient(cc *grpc.ClientConn) DictionaryServiceClient {
	return &dictionaryServiceClient{cc}
}

func (c *dictionaryServiceClient) Get(ctx context.Context, in *DictionaryRequest, opts ...grpc.CallOption) (*DictionaryResponse, error) {
	out := new(DictionaryResponse)
	err := c.cc.Invoke(ctx, "/protobuf.DictionaryService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DictionaryServiceServer is the server API for DictionaryService service.
type DictionaryServiceServer interface {
	// Sends a greeting
	Get(context.Context, *DictionaryRequest) (*DictionaryResponse, error)
}

func RegisterDictionaryServiceServer(s *grpc.Server, srv DictionaryServiceServer) {
	s.RegisterService(&_DictionaryService_serviceDesc, srv)
}

func _DictionaryService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictionaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.DictionaryService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServiceServer).Get(ctx, req.(*DictionaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DictionaryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.DictionaryService",
	HandlerType: (*DictionaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _DictionaryService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dictionary.proto",
}

func init() { proto.RegisterFile("dictionary.proto", fileDescriptor_dictionary_06b32c1b60cef4cf) }

var fileDescriptor_dictionary_06b32c1b60cef4cf = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xdd, 0x4a, 0xfb, 0x40,
	0x10, 0xc5, 0xff, 0x49, 0x9a, 0x7e, 0x4c, 0xff, 0xf8, 0xb1, 0x28, 0x2c, 0x56, 0x31, 0xf6, 0x2a,
	0x57, 0x51, 0xea, 0x1b, 0x04, 0x41, 0xbc, 0x2b, 0x51, 0xf0, 0xb2, 0x6c, 0xb3, 0xa3, 0x2e, 0x34,
	0xdd, 0x35, 0xbb, 0x29, 0xe4, 0x3d, 0x7c, 0x60, 0xc9, 0x24, 0xd1, 0x82, 0xe2, 0x55, 0x66, 0xe6,
	0xfc, 0xe6, 0x30, 0x39, 0x0b, 0x47, 0x52, 0xe5, 0x4e, 0xe9, 0xad, 0x28, 0xeb, 0xc4, 0x94, 0xda,
	0x69, 0x36, 0xa6, 0xcf, 0xba, 0x7a, 0x99, 0x7f, 0xf8, 0x70, 0x7c, 0xf7, 0x25, 0x67, 0xf8, 0x5e,
	0xa1, 0x75, 0xec, 0x00, 0x7c, 0x25, 0xb9, 0x17, 0x79, 0xf1, 0x24, 0xf3, 0x95, 0x64, 0x0c, 0x06,
	0x5b, 0x51, 0x20, 0xf7, 0x69, 0x42, 0x35, 0x3b, 0x85, 0xa1, 0x30, 0x66, 0xa5, 0x24, 0x0f, 0x22,
	0x2f, 0x0e, 0xb2, 0x50, 0x18, 0xf3, 0x40, 0xa8, 0xab, 0x0d, 0xf2, 0x41, 0xe4, 0xc5, 0x61, 0x46,
	0x35, 0x3b, 0x81, 0x70, 0x27, 0x36, 0x15, 0xf2, 0x90, 0xf6, 0xdb, 0x86, 0x5d, 0x00, 0xe4, 0x25,
	0x0a, 0x87, 0x72, 0xb5, 0xae, 0xf9, 0x90, 0x4c, 0x26, 0xdd, 0x24, 0xad, 0x1b, 0xb9, 0x32, 0xb2,
	0x97, 0x47, 0xad, 0xdc, 0x4d, 0xd2, 0x9a, 0x5d, 0xc1, 0xff, 0x7e, 0xdb, 0xa9, 0x02, 0xf9, 0x98,
	0x80, 0x69, 0x37, 0x7b, 0x52, 0x05, 0xb2, 0x4b, 0x98, 0xb6, 0x7c, 0x4b, 0x4c, 0x88, 0xe8, 0x4c,
	0x09, 0xe0, 0x30, 0x92, 0xb8, 0x41, 0x87, 0x92, 0x03, 0x9d, 0xdb, 0xb7, 0x73, 0x0b, 0x6c, 0x3f,
	0x15, 0x6b, 0xf4, 0xd6, 0x62, 0xf3, 0x6f, 0xb9, 0x96, 0x48, 0xc1, 0x84, 0x19, 0xd5, 0x8d, 0x47,
	0x81, 0xd6, 0x8a, 0xd7, 0x3e, 0x9d, 0xbe, 0x65, 0xd7, 0x30, 0x90, 0xc2, 0x09, 0x1e, 0x44, 0x41,
	0x3c, 0x5d, 0xcc, 0x92, 0x3e, 0xf3, 0xe4, 0x47, 0xde, 0x19, 0x81, 0x8b, 0xe7, 0xfd, 0xa7, 0x78,
	0xc4, 0x72, 0xa7, 0x72, 0x64, 0x29, 0x04, 0xf7, 0xe8, 0xd8, 0x5f, 0xeb, 0x67, 0xe7, 0xbf, 0x8b,
	0xed, 0xd5, 0xf3, 0x7f, 0xe9, 0x0d, 0xcc, 0x94, 0x4e, 0x24, 0xee, 0xb4, 0xb1, 0xc9, 0x9b, 0xca,
	0x55, 0x2e, 0xf7, 0xc0, 0xf4, 0xf0, 0xbb, 0x5e, 0x36, 0x3e, 0x4b, 0x6f, 0x3d, 0x24, 0xc3, 0xdb,
	0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x27, 0x58, 0xea, 0x72, 0x3b, 0x02, 0x00, 0x00,
}
