// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package protobuf

/*
target package name
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProfileRequest struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProfileId            string      `protobuf:"bytes,3,opt,name=profileId,proto3" json:"profileId,omitempty"`
	Namespace            string      `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Host                 string      `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	Rebuild              bool        `protobuf:"varint,6,opt,name=rebuild,proto3" json:"rebuild,omitempty"`
	Deploy               bool        `protobuf:"varint,7,opt,name=deploy,proto3" json:"deploy,omitempty"`
	Gateway              string      `protobuf:"bytes,8,opt,name=gateway,proto3" json:"gateway,omitempty"`
	BuildEnable          bool        `protobuf:"varint,9,opt,name=build_enable,json=buildEnable,proto3" json:"build_enable,omitempty"`
	RemoteEnable         bool        `protobuf:"varint,10,opt,name=remote_enable,json=remoteEnable,proto3" json:"remote_enable,omitempty"`
	TagEnable            bool        `protobuf:"varint,11,opt,name=tag_enable,json=tagEnable,proto3" json:"tag_enable,omitempty"`
	ImageTags            []*ImageTag `protobuf:"bytes,12,rep,name=image_tags,json=imageTags,proto3" json:"image_tags,omitempty"`
	ScmRef               string      `protobuf:"bytes,13,opt,name=scm_ref,json=scmRef,proto3" json:"scm_ref,omitempty"`
	IstioEnable          bool        `protobuf:"varint,14,opt,name=istio_enable,json=istioEnable,proto3" json:"istio_enable,omitempty"`
	CreatedTime          string      `protobuf:"bytes,15,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	CreatedBy            string      `protobuf:"bytes,16,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedTime          string      `protobuf:"bytes,17,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	UpdatedBy            string      `protobuf:"bytes,18,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Deleted              int32       `protobuf:"varint,19,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProfileRequest) Reset()         { *m = ProfileRequest{} }
func (m *ProfileRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileRequest) ProtoMessage()    {}
func (*ProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_profile_47105ccb12fd3094, []int{0}
}
func (m *ProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileRequest.Unmarshal(m, b)
}
func (m *ProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileRequest.Marshal(b, m, deterministic)
}
func (dst *ProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileRequest.Merge(dst, src)
}
func (m *ProfileRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileRequest.Size(m)
}
func (m *ProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileRequest proto.InternalMessageInfo

func (m *ProfileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProfileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProfileRequest) GetProfileId() string {
	if m != nil {
		return m.ProfileId
	}
	return ""
}

func (m *ProfileRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ProfileRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ProfileRequest) GetRebuild() bool {
	if m != nil {
		return m.Rebuild
	}
	return false
}

func (m *ProfileRequest) GetDeploy() bool {
	if m != nil {
		return m.Deploy
	}
	return false
}

func (m *ProfileRequest) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *ProfileRequest) GetBuildEnable() bool {
	if m != nil {
		return m.BuildEnable
	}
	return false
}

func (m *ProfileRequest) GetRemoteEnable() bool {
	if m != nil {
		return m.RemoteEnable
	}
	return false
}

func (m *ProfileRequest) GetTagEnable() bool {
	if m != nil {
		return m.TagEnable
	}
	return false
}

func (m *ProfileRequest) GetImageTags() []*ImageTag {
	if m != nil {
		return m.ImageTags
	}
	return nil
}

func (m *ProfileRequest) GetScmRef() string {
	if m != nil {
		return m.ScmRef
	}
	return ""
}

func (m *ProfileRequest) GetIstioEnable() bool {
	if m != nil {
		return m.IstioEnable
	}
	return false
}

func (m *ProfileRequest) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

func (m *ProfileRequest) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *ProfileRequest) GetUpdatedTime() string {
	if m != nil {
		return m.UpdatedTime
	}
	return ""
}

func (m *ProfileRequest) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *ProfileRequest) GetDeleted() int32 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

type ProfileResponse struct {
	Code                 int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *ProfileRequest `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProfileResponse) Reset()         { *m = ProfileResponse{} }
func (m *ProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileResponse) ProtoMessage()    {}
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_profile_47105ccb12fd3094, []int{1}
}
func (m *ProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileResponse.Unmarshal(m, b)
}
func (m *ProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileResponse.Marshal(b, m, deterministic)
}
func (dst *ProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileResponse.Merge(dst, src)
}
func (m *ProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileResponse.Size(m)
}
func (m *ProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileResponse proto.InternalMessageInfo

func (m *ProfileResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ProfileResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ProfileResponse) GetData() *ProfileRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

type ImageTag struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProfileId            string   `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Repository           string   `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Tag                  string   `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	Text                 string   `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Value                string   `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageTag) Reset()         { *m = ImageTag{} }
func (m *ImageTag) String() string { return proto.CompactTextString(m) }
func (*ImageTag) ProtoMessage()    {}
func (*ImageTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_profile_47105ccb12fd3094, []int{2}
}
func (m *ImageTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageTag.Unmarshal(m, b)
}
func (m *ImageTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageTag.Marshal(b, m, deterministic)
}
func (dst *ImageTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageTag.Merge(dst, src)
}
func (m *ImageTag) XXX_Size() int {
	return xxx_messageInfo_ImageTag.Size(m)
}
func (m *ImageTag) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageTag.DiscardUnknown(m)
}

var xxx_messageInfo_ImageTag proto.InternalMessageInfo

func (m *ImageTag) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ImageTag) GetProfileId() string {
	if m != nil {
		return m.ProfileId
	}
	return ""
}

func (m *ImageTag) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *ImageTag) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *ImageTag) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *ImageTag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ImageTag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ProfileRequest)(nil), "protobuf.ProfileRequest")
	proto.RegisterType((*ProfileResponse)(nil), "protobuf.ProfileResponse")
	proto.RegisterType((*ImageTag)(nil), "protobuf.ImageTag")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileServiceClient interface {
	// Sends a greeting
	Get(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
}

type profileServiceClient struct {
	cc *grpc.ClientConn
}

func NewProfileServiceClient(cc *grpc.ClientConn) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) Get(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/protobuf.ProfileService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
type ProfileServiceServer interface {
	// Sends a greeting
	Get(context.Context, *ProfileRequest) (*ProfileResponse, error)
}

func RegisterProfileServiceServer(s *grpc.Server, srv ProfileServiceServer) {
	s.RegisterService(&_ProfileService_serviceDesc, srv)
}

func _ProfileService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ProfileService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Get(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ProfileService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile.proto",
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor_profile_47105ccb12fd3094) }

var fileDescriptor_profile_47105ccb12fd3094 = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xcd, 0x8e, 0xd3, 0x3c,
	0x14, 0xfd, 0x32, 0xfd, 0xcd, 0xed, 0xcf, 0xcc, 0x67, 0x10, 0x78, 0x10, 0x83, 0x3a, 0x65, 0x53,
	0x09, 0x14, 0x89, 0xb2, 0x65, 0x55, 0x09, 0xa1, 0xd9, 0xa0, 0x2a, 0xcc, 0xbe, 0x72, 0xe2, 0xdb,
	0x8c, 0xa5, 0xa4, 0x0e, 0xb1, 0x5b, 0xe8, 0x23, 0xf1, 0x1e, 0x3c, 0x18, 0xf2, 0x8d, 0xdd, 0x0e,
	0x02, 0x56, 0xb9, 0xf7, 0x9c, 0xe3, 0x63, 0xfb, 0xe6, 0x18, 0x26, 0x75, 0xa3, 0xb7, 0xaa, 0xc4,
	0xa4, 0x6e, 0xb4, 0xd5, 0x6c, 0x48, 0x9f, 0x6c, 0xbf, 0x9d, 0xff, 0xec, 0xc2, 0x74, 0xdd, 0x72,
	0x29, 0x7e, 0xdd, 0xa3, 0xb1, 0x6c, 0x0a, 0x17, 0x4a, 0xf2, 0x68, 0x16, 0x2d, 0xe2, 0xf4, 0x42,
	0x49, 0xc6, 0xa0, 0xbb, 0x13, 0x15, 0xf2, 0x0b, 0x42, 0xa8, 0x66, 0x2f, 0x21, 0xf6, 0x8e, 0x77,
	0x92, 0x77, 0x88, 0x38, 0x03, 0x8e, 0x75, 0x2a, 0x53, 0x8b, 0x1c, 0x79, 0xb7, 0x65, 0x4f, 0x80,
	0xf3, 0x7b, 0xd0, 0xc6, 0xf2, 0x5e, 0xeb, 0xe7, 0x6a, 0xc6, 0x61, 0xd0, 0x60, 0xb6, 0x57, 0xa5,
	0xe4, 0xfd, 0x59, 0xb4, 0x18, 0xa6, 0xa1, 0x65, 0xcf, 0xa0, 0x2f, 0xb1, 0x2e, 0xf5, 0x91, 0x0f,
	0x88, 0xf0, 0x9d, 0x5b, 0x51, 0x08, 0x8b, 0xdf, 0xc4, 0x91, 0x0f, 0xc9, 0x28, 0xb4, 0xec, 0x16,
	0xc6, 0xb4, 0x74, 0x83, 0x3b, 0x91, 0x95, 0xc8, 0x63, 0x5a, 0x37, 0x22, 0xec, 0x23, 0x41, 0xec,
	0x35, 0x4c, 0x1a, 0xac, 0xb4, 0xc5, 0xa0, 0x01, 0xd2, 0x8c, 0x5b, 0xd0, 0x8b, 0x6e, 0x00, 0xac,
	0x28, 0x82, 0x62, 0x44, 0x8a, 0xd8, 0x8a, 0xc2, 0xd3, 0xef, 0x00, 0x54, 0x25, 0x0a, 0xdc, 0x58,
	0x51, 0x18, 0x3e, 0x9e, 0x75, 0x16, 0xa3, 0x25, 0x4b, 0xc2, 0x60, 0x93, 0x3b, 0xc7, 0xdd, 0x8b,
	0x22, 0x8d, 0x95, 0xaf, 0x0c, 0x7b, 0x0e, 0x03, 0x93, 0x57, 0x9b, 0x06, 0xb7, 0x7c, 0x42, 0x67,
	0xee, 0x9b, 0xbc, 0x4a, 0x71, 0xeb, 0x8e, 0xac, 0x8c, 0x55, 0x3a, 0x6c, 0x36, 0x6d, 0x8f, 0x4c,
	0x98, 0xdf, 0xee, 0x16, 0xc6, 0x79, 0x83, 0xc2, 0xa2, 0xdc, 0x58, 0x55, 0x21, 0xbf, 0x24, 0x83,
	0x91, 0xc7, 0xee, 0x55, 0x45, 0x07, 0x0e, 0x92, 0xec, 0xc8, 0xaf, 0xda, 0xb9, 0x7b, 0x64, 0x45,
	0x73, 0xd9, 0xd7, 0xf2, 0xec, 0xf0, 0x7f, 0xeb, 0xe0, 0xb1, 0xe0, 0x10, 0x24, 0xd9, 0x91, 0xb3,
	0xd6, 0xc1, 0x23, 0x2b, 0x9a, 0xb9, 0xc4, 0x12, 0x2d, 0x4a, 0xfe, 0x64, 0x16, 0x2d, 0x7a, 0x69,
	0x68, 0xe7, 0x15, 0x5c, 0x9e, 0x52, 0x64, 0x6a, 0xbd, 0x33, 0xf4, 0x9b, 0x73, 0x2d, 0x91, 0x82,
	0xd4, 0x4b, 0xa9, 0x76, 0x06, 0x15, 0x1a, 0x23, 0x8a, 0x90, 0xa6, 0xd0, 0xb2, 0xb7, 0xd0, 0x95,
	0xc2, 0x0a, 0xca, 0xd2, 0x68, 0xc9, 0xcf, 0x73, 0xfc, 0x3d, 0x9c, 0x29, 0xa9, 0xe6, 0x3f, 0x22,
	0x18, 0x86, 0x01, 0xff, 0x91, 0xd7, 0x1b, 0x00, 0x1f, 0xc5, 0x8d, 0x92, 0x7e, 0x9f, 0x47, 0xe1,
	0x7c, 0x05, 0xd0, 0x60, 0xad, 0x8d, 0xb2, 0xba, 0x39, 0xfa, 0xec, 0x3e, 0x42, 0xd8, 0x15, 0x74,
	0xac, 0x28, 0x7c, 0x6c, 0x5d, 0xe9, 0x6e, 0x62, 0xf1, 0xfb, 0x29, 0xb0, 0xae, 0x66, 0x4f, 0xa1,
	0x77, 0x10, 0xe5, 0x1e, 0x29, 0xae, 0x71, 0xda, 0x36, 0xa7, 0xa7, 0x32, 0x38, 0x3f, 0x95, 0xe5,
	0xe7, 0xd3, 0x03, 0xfb, 0x82, 0xcd, 0x41, 0xe5, 0xc8, 0x3e, 0x40, 0xe7, 0x13, 0x5a, 0xf6, 0xcf,
	0x4b, 0xbe, 0xb8, 0xfe, 0x0b, 0xd3, 0x4e, 0x75, 0xfe, 0xdf, 0xea, 0x0d, 0x5c, 0x2b, 0x9d, 0x48,
	0x3c, 0xe8, 0xda, 0x24, 0x0f, 0x4a, 0xc8, 0x4a, 0xed, 0x12, 0x7f, 0xbd, 0xd5, 0xd8, 0xeb, 0xd7,
	0x6e, 0xfd, 0x3a, 0xca, 0xfa, 0x64, 0xf4, 0xfe, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xd7,
	0x60, 0x79, 0x00, 0x04, 0x00, 0x00,
}
