// Code generated by protoc-gen-go. DO NOT EDIT.
// source: remotedeployment.proto

package protobuf

/*
target package name
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RemoteDeploymentRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Project              string   `protobuf:"bytes,3,opt,name=Project,proto3" json:"Project,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=Version,proto3" json:"Version,omitempty"`
	Profile              string   `protobuf:"bytes,5,opt,name=Profile,proto3" json:"Profile,omitempty"`
	RegistryUrl          string   `protobuf:"bytes,6,opt,name=RegistryUrl,proto3" json:"RegistryUrl,omitempty"`
	RemoteUrl            string   `protobuf:"bytes,7,opt,name=RemoteUrl,proto3" json:"RemoteUrl,omitempty"`
	DockerRegistry       string   `protobuf:"bytes,8,opt,name=DockerRegistry,proto3" json:"DockerRegistry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteDeploymentRequest) Reset()         { *m = RemoteDeploymentRequest{} }
func (m *RemoteDeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*RemoteDeploymentRequest) ProtoMessage()    {}
func (*RemoteDeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_remotedeployment_6a3ee46fd2185825, []int{0}
}
func (m *RemoteDeploymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteDeploymentRequest.Unmarshal(m, b)
}
func (m *RemoteDeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteDeploymentRequest.Marshal(b, m, deterministic)
}
func (dst *RemoteDeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteDeploymentRequest.Merge(dst, src)
}
func (m *RemoteDeploymentRequest) XXX_Size() int {
	return xxx_messageInfo_RemoteDeploymentRequest.Size(m)
}
func (m *RemoteDeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteDeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteDeploymentRequest proto.InternalMessageInfo

func (m *RemoteDeploymentRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RemoteDeploymentRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *RemoteDeploymentRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *RemoteDeploymentRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *RemoteDeploymentRequest) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *RemoteDeploymentRequest) GetRegistryUrl() string {
	if m != nil {
		return m.RegistryUrl
	}
	return ""
}

func (m *RemoteDeploymentRequest) GetRemoteUrl() string {
	if m != nil {
		return m.RemoteUrl
	}
	return ""
}

func (m *RemoteDeploymentRequest) GetDockerRegistry() string {
	if m != nil {
		return m.DockerRegistry
	}
	return ""
}

type RemoteDeploymentResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteDeploymentResponse) Reset()         { *m = RemoteDeploymentResponse{} }
func (m *RemoteDeploymentResponse) String() string { return proto.CompactTextString(m) }
func (*RemoteDeploymentResponse) ProtoMessage()    {}
func (*RemoteDeploymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_remotedeployment_6a3ee46fd2185825, []int{1}
}
func (m *RemoteDeploymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteDeploymentResponse.Unmarshal(m, b)
}
func (m *RemoteDeploymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteDeploymentResponse.Marshal(b, m, deterministic)
}
func (dst *RemoteDeploymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteDeploymentResponse.Merge(dst, src)
}
func (m *RemoteDeploymentResponse) XXX_Size() int {
	return xxx_messageInfo_RemoteDeploymentResponse.Size(m)
}
func (m *RemoteDeploymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteDeploymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteDeploymentResponse proto.InternalMessageInfo

func (m *RemoteDeploymentResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RemoteDeploymentResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RemoteDeploymentResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*RemoteDeploymentRequest)(nil), "protobuf.RemoteDeploymentRequest")
	proto.RegisterType((*RemoteDeploymentResponse)(nil), "protobuf.RemoteDeploymentResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RemoteDeploymentServiceClient is the client API for RemoteDeploymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoteDeploymentServiceClient interface {
	// Sends a greeting
	Get(ctx context.Context, in *RemoteDeploymentRequest, opts ...grpc.CallOption) (*RemoteDeploymentResponse, error)
}

type remoteDeploymentServiceClient struct {
	cc *grpc.ClientConn
}

func NewRemoteDeploymentServiceClient(cc *grpc.ClientConn) RemoteDeploymentServiceClient {
	return &remoteDeploymentServiceClient{cc}
}

func (c *remoteDeploymentServiceClient) Get(ctx context.Context, in *RemoteDeploymentRequest, opts ...grpc.CallOption) (*RemoteDeploymentResponse, error) {
	out := new(RemoteDeploymentResponse)
	err := c.cc.Invoke(ctx, "/protobuf.RemoteDeploymentService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteDeploymentServiceServer is the server API for RemoteDeploymentService service.
type RemoteDeploymentServiceServer interface {
	// Sends a greeting
	Get(context.Context, *RemoteDeploymentRequest) (*RemoteDeploymentResponse, error)
}

func RegisterRemoteDeploymentServiceServer(s *grpc.Server, srv RemoteDeploymentServiceServer) {
	s.RegisterService(&_RemoteDeploymentService_serviceDesc, srv)
}

func _RemoteDeploymentService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoteDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteDeploymentServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.RemoteDeploymentService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteDeploymentServiceServer).Get(ctx, req.(*RemoteDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RemoteDeploymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.RemoteDeploymentService",
	HandlerType: (*RemoteDeploymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _RemoteDeploymentService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remotedeployment.proto",
}

func init() {
	proto.RegisterFile("remotedeployment.proto", fileDescriptor_remotedeployment_6a3ee46fd2185825)
}

var fileDescriptor_remotedeployment_6a3ee46fd2185825 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x3d, 0x4f, 0xc3, 0x30,
	0x14, 0x24, 0x6d, 0xd3, 0x0f, 0x57, 0x62, 0xb0, 0x50, 0xb1, 0x10, 0x43, 0xc9, 0x00, 0x4c, 0x19,
	0xe0, 0x1f, 0x54, 0x95, 0xd8, 0xaa, 0x28, 0x7c, 0x4c, 0x2c, 0xae, 0xf3, 0x1a, 0x4c, 0x93, 0xbc,
	0x60, 0xbb, 0x48, 0x9d, 0xf9, 0xe3, 0xc8, 0x76, 0x12, 0x10, 0x15, 0x9d, 0xe2, 0x7b, 0x77, 0x67,
	0x5d, 0xee, 0x99, 0xcc, 0x14, 0x94, 0x68, 0x20, 0x83, 0xba, 0xc0, 0x7d, 0x09, 0x95, 0x89, 0x6b,
	0x85, 0x06, 0xe9, 0xd8, 0x7d, 0xd6, 0xbb, 0x4d, 0xf4, 0xd5, 0x23, 0xe7, 0xa9, 0x13, 0x2d, 0x3b,
	0x51, 0x0a, 0x1f, 0x3b, 0xd0, 0x86, 0x9e, 0x91, 0xf0, 0x09, 0xb7, 0x50, 0xb1, 0x60, 0x1e, 0xdc,
	0x4e, 0x52, 0x0f, 0xe8, 0x25, 0x99, 0xac, 0x78, 0x09, 0xba, 0xe6, 0x02, 0x58, 0xcf, 0x31, 0x3f,
	0x03, 0xca, 0xc8, 0x28, 0x51, 0xf8, 0x0e, 0xc2, 0xb0, 0xbe, 0xe3, 0x5a, 0x68, 0x99, 0x17, 0x50,
	0x5a, 0x62, 0xc5, 0x06, 0x9e, 0x69, 0x60, 0xe3, 0xd9, 0xc8, 0x02, 0x58, 0xd8, 0x79, 0x2c, 0xa4,
	0x73, 0x32, 0x4d, 0x21, 0x97, 0xda, 0xa8, 0xfd, 0xb3, 0x2a, 0xd8, 0xd0, 0xb1, 0xbf, 0x47, 0x36,
	0x8d, 0x8f, 0x6f, 0xf9, 0x91, 0x4f, 0xd3, 0x0d, 0xe8, 0x35, 0x39, 0x5d, 0xa2, 0xd8, 0x82, 0x6a,
	0x2d, 0x6c, 0xec, 0x24, 0x7f, 0xa6, 0xd1, 0x2b, 0x61, 0x87, 0x25, 0xe8, 0x1a, 0x2b, 0x0d, 0x94,
	0x92, 0x81, 0xc0, 0x0c, 0x5c, 0x09, 0x61, 0xea, 0xce, 0x36, 0x71, 0x09, 0x5a, 0xf3, 0xbc, 0x6d,
	0xa0, 0x85, 0x56, 0x9d, 0x71, 0xc3, 0x9b, 0x9f, 0x77, 0xe7, 0x3b, 0x79, 0x58, 0xf1, 0x23, 0xa8,
	0x4f, 0x29, 0x80, 0xae, 0x48, 0xff, 0x01, 0x0c, 0xbd, 0x8a, 0xdb, 0x85, 0xc4, 0xff, 0x2c, 0xe3,
	0x22, 0x3a, 0x26, 0xf1, 0x51, 0xa3, 0x93, 0xc5, 0x0d, 0x99, 0x49, 0x8c, 0x73, 0x55, 0x8b, 0xf8,
	0x4d, 0xf2, 0xdc, 0x6e, 0xdc, 0x3f, 0x81, 0xc5, 0xd4, 0xbb, 0x12, 0x7b, 0x49, 0x12, 0xac, 0x87,
	0xee, 0xb6, 0xfb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x57, 0x7d, 0xf1, 0x22, 0x02, 0x00,
	0x00,
}
