
pipeline:
  name: java-war
  identifiers:
  - pom.xml
  buildConfigs:
    imagestream: s2i-java-war:1.0.6
    env:
    - name: TZ
      value: Asia/Shanghai
    - name: MAVEN_MIRROR_URL
      value: ${MAVEN_MIRROR_URL}
    - name: MAVEN_CLEAR_REPO
      value: false
    - name: BUILD_SCRIPT
      value: |
        mvn clean package -U -Dmaven.test.skip=true -Djava.net.preferIPv4Stack=true
        if [[ $? == 0 ]]; then
          echo "Build Successful."
        else
          echo "Build Failed!"
          exit 1
        fi
  deploymentConfigs:
    healthEndPoint: http://localhost:8080/health
    env:
    - name: APP_OPTIONS
      value: -Xms128m -Xmx512m -Xss512k
    - name: SPRING_PROFILES_ACTIVE
      value: ${profile}